# config/promtail/promtail-config.yml

# Настройки сервера Promtail (служебный порт)
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Где искать Loki
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# --- Самая важная часть: откуда собирать логи ---
scrape_configs:
  - job_name: system
    # Этот блок говорит Promtail следить за логами Docker-контейнеров
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # Этот блок говорит, как обрабатывать найденные логи
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      # Мы берем стандартные метки от Docker и превращаем их
      # в красивые метки для Loki
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'